### ISSUE TITLE
make the "about tab" a drop down to include: "our history", "What we do", and "our team"

### ISSUE THREAD

**Issue by mzeleke** [GWIC/dub.works#55]
ideally, all three sections should be on one page. When you click on one of them it just takes you to that section of the page.

**Comment by omn0mn0m** [comment]
```css
.dropdown:hover .dropdown-content {
    display: block;
}
```
