### ISSUE TITLE
make "events page" a drop down to include: "upcoming events", "Request Space", and "past events"

### ISSUE THREAD

**Issue by mzeleke** [GWIC/dub.works#58]

**Comment by omn0mn0m** [comment]
```css
.dropdown:hover .dropdown-content {
    display: block;
}
```
