### ISSUE TITLE
make a separate tab: "dub works" make it drop down tab to include: "virtual tour" and "3D printing"

### ISSUE THREAD

**Issue by mzeleke** [GWIC/dub.works#62]
the current printing page will now go under dubworks and removed from header

**Comment by omn0mn0m** [comment]
```css
.dropdown:hover .dropdown-content {
    display: block;
}
```
